spring:
  datasource:
    url: jdbc:mysql://xxx.xxx.xxx:3306/spring_security_study
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
